version: '3.8'

services:

  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
  redis_data: